Upgraded snakemake and now use mamba frontend. Also made some output files as temporary

diff --git a/juno-salmonella b/juno-salmonella
--- a/juno-salmonella
+++ b/juno-salmonella
@@ -136,6 +136,11 @@ if [ "${CLEAN:-}" == "TRUE" ]; then
 fi
 
 
+###############################################################################################################
+##### Create mamba environment if it doesn exist                                                          #####
+###############################################################################################################
+conda env update -f envs/mamba.yaml -q -v
+source activate mamba
 
 ###############################################################################################################
 ##### Installation block                                                                                  #####
@@ -152,40 +157,33 @@ fi
 if [[ $PATH != *${MASTER_NAME}* ]]; then # If the master environment is not in your path (i.e. it is not currently active), do...
     line
     spacer
-    set +ue # Turn bash strict mode off because that breaks conda
-    conda activate "${MASTER_NAME}" # Try to activate this env
-    if [ ! $? -eq 0 ]; then # If exit statement is not 0, i.e. master conda env hasn't been installed yet, do...
-        #installer_intro
-        if [ "${SKIP_CONFIRMATION}" = "TRUE" ]; then
-            echo -e "\tInstalling master environment..." 
-            conda env update -f envs/mamba.yaml -q -v
-            source activate mamba
-            mamba env update -f ${PATH_MASTER_YAML}
-            conda activate "${MASTER_NAME}"
-            echo -e "DONE"
-        else
-            while read -r -p "The master environment hasn't been installed yet, do you want to install this environment now? [y/n] " envanswer
-            do
-                envanswer=${envanswer,,}
-                if [[ "${envanswer}" =~ ^(yes|y)$ ]]; then
-                    echo -e "\tInstalling master environment..." 
-                    conda env update -f envs/mamba.yaml -q -v
-                    source activate mamba
-                    mamba env update -f ${PATH_MASTER_YAML}
-                    conda activate "${MASTER_NAME}"
-                    echo -e "DONE"
-                    break
-                elif [[ "${envanswer}" =~ ^(no|n)$ ]]; then
-                    echo -e "The master environment is a requirement. Exiting because cannot continue without this environment"
-                    exit 1
-                else
-                    echo -e "Please answer with 'yes' or 'no'"
-                fi
-            done
-        fi
+    source activate ${MASTER_NAME}
+    if [ ! $? -eq 0 ]; then
+    	set +ue # Turn bash strict mode off because that breaks conda
+    	if [ "${SKIP_CONFIRMATION}" = "TRUE" ]; then
+       		echo -e "\tInstalling master environment..." 
+       		mamba env update -f ${PATH_MASTER_YAML} 
+       		echo -e "DONE"
+    	else
+       		while read -r -p "The master environment hasn't been installed yet, do you want to install this environment now? [y/n] " envanswer
+       		do
+            		envanswer=${envanswer,,}
+            		if [[ "${envanswer}" =~ ^(yes|y)$ ]]; then
+                		echo -e "\tInstalling master environment..." 
+				mamba env update -f ${PATH_MASTER_YAML}
+                		echo -e "DONE"
+                		break
+            		elif [[ "${envanswer}" =~ ^(no|n)$ ]]; then
+                		echo -e "The master environment is a requirement. Exiting because Juno cannot continue without this environment"
+                		exit 1
+            		else
+                		echo -e "Please answer with 'yes' or 'no'"
+            		fi
+        	done
+    	fi
     fi
+    source activate "${MASTER_NAME}"
     set -ue # Turn bash strict mode on again
-    echo -e "Succesfully activated master environment"
 fi
 
 
